/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Date;
import javax.swing.JOptionPane;
import modelo.DoadorVO;
import modelo.LoginVO;
import servicos.DoadorServicos;
import servicos.ServicosFactory;

/**
 *
 * @author cruza
 */
public class GUICadastrarSe extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadastrarSe
     */
    public GUICadastrarSe() {
        initComponents();
        
        //Mascara para o campo data e limitador de caracteres
        jtfNascimento.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (jtfNascimento.getText().length() == 10 || !Character.isDigit(c)) {
                    e.consume(); // Impede a digitação de caracteres não numéricos ou além do limite de 10 caracteres.
                } else if (jtfNascimento.getText().length() == 2 || jtfNascimento.getText().length() == 5) {
                    jtfNascimento.setText(jtfNascimento.getText() + "/");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTipoSanguinio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNascimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfUF = new javax.swing.JTextField();
        jbtnCadastrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jpfSenha = new javax.swing.JPasswordField();
        jrbtnAMais = new javax.swing.JRadioButton();
        jrbtnBMais = new javax.swing.JRadioButton();
        jrbtnABMais = new javax.swing.JRadioButton();
        jrbtnOMais = new javax.swing.JRadioButton();
        jrbtnAMenos = new javax.swing.JRadioButton();
        jrbtnBMenos = new javax.swing.JRadioButton();
        jrbtnABMenos = new javax.swing.JRadioButton();
        jrbtnOMenos = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Usuário");

        jLabel1.setText("Nome Completo");

        jLabel2.setText("Data de Nascimento");

        jtfNascimento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNascimento.setText("31/12/1999");
        jtfNascimento.setToolTipText("Exemplo: 01/01/1980");
        jtfNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNascimentoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNascimentoFocusLost(evt);
            }
        });

        jLabel3.setText("Tipo Sanguínio");

        jLabel7.setText("Bairro");

        jLabel8.setText("Cidade");

        jLabel9.setText("UF");

        jbtnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });

        jLabel10.setText("E-mail");

        jLabel11.setText("Senha");

        bgTipoSanguinio.add(jrbtnAMais);
        jrbtnAMais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnAMais.setText("A+");
        jrbtnAMais.setActionCommand("A+");

        bgTipoSanguinio.add(jrbtnBMais);
        jrbtnBMais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnBMais.setText("B+");
        jrbtnBMais.setActionCommand("B+");

        bgTipoSanguinio.add(jrbtnABMais);
        jrbtnABMais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnABMais.setText("AB+");
        jrbtnABMais.setActionCommand("AB+");

        bgTipoSanguinio.add(jrbtnOMais);
        jrbtnOMais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnOMais.setText("O+");
        jrbtnOMais.setActionCommand("O+");

        bgTipoSanguinio.add(jrbtnAMenos);
        jrbtnAMenos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnAMenos.setText("A-");
        jrbtnAMenos.setActionCommand("A-");

        bgTipoSanguinio.add(jrbtnBMenos);
        jrbtnBMenos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnBMenos.setText("B-");
        jrbtnBMenos.setActionCommand("B-");

        bgTipoSanguinio.add(jrbtnABMenos);
        jrbtnABMenos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnABMenos.setText("AB-");
        jrbtnABMenos.setActionCommand("AB-");

        bgTipoSanguinio.add(jrbtnOMenos);
        jrbtnOMenos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jrbtnOMenos.setText("O-");
        jrbtnOMenos.setActionCommand("O-");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Ao digitar as \" / \" são colocadas automaticamente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBairro))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCidade)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpfSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnAMais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnAMenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnBMais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnBMenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnABMais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnABMenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnOMais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrbtnOMenos)))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jbtnCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbtnABMenos)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jrbtnOMais)
                                .addComponent(jrbtnOMenos))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jrbtnAMais)
                                .addComponent(jrbtnAMenos)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jrbtnABMais, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jrbtnBMais)
                                    .addComponent(jrbtnBMenos))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarDoador() {

        try {                  
            DoadorVO cdVO = new DoadorVO();
                       
            cdVO.setNomeDoador(jtfNome.getText());
            cdVO.setDataNascDoadorMySQL(jtfNascimento.getText());
            cdVO.setTipoSanguinioDoador(bgTipoSanguinio.getSelection().getActionCommand());
            cdVO.setEmailDoador(jtfEmail.getText());
            cdVO.setEndBairroDoador(jtfBairro.getText());
            cdVO.setEndCidadeDoador(jtfCidade.getText());
            cdVO.setEndUFDoador(jtfUF.getText());
            
            LoginVO lVO = new LoginVO();
            
            lVO.setUsrLogin(jtfEmail.getText());
            lVO.setSenhaLogin(jpfSenha.getText());

            /**
             * Enviar o objeto cdVO para o Banco de Dados. O envio é através de
             * servicos, porém antes passa pela produtoDAO
             *
             */
            DoadorServicos ds = ServicosFactory.getDoadorServicos();

            //chamando o método
            ds.cadastrarDoador(cdVO, lVO);

            //retorno para o usuário
            JOptionPane.showMessageDialog(null, "Doador cadastrato com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro na GUICadastrarSe " + e.getMessage(), "Erro!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
     private void limpar() {
        jtfNome.setText("");
        jtfNascimento.setText("30/01/1980");
        bgTipoSanguinio.clearSelection();
        jtfEmail.setText("");
        jtfBairro.setText("");
        jtfCidade.setText("");
        jtfUF.setText("");
        jpfSenha.setText("");
    }


    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        // TODO add your handling code here:
        cadastrarDoador();
        limpar();
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private void jtfNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNascimentoFocusGained
        // TODO add your handling code here:
        jtfNascimento.setText("");
    }//GEN-LAST:event_jtfNascimentoFocusGained

    private void jtfNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNascimentoFocusLost
        // TODO add your handling code here:
        if ("".equals(jtfNascimento.getText())) {
            jtfNascimento.setText("30/01/1980");
        }
    }//GEN-LAST:event_jtfNascimentoFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoSanguinio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JRadioButton jrbtnABMais;
    private javax.swing.JRadioButton jrbtnABMenos;
    private javax.swing.JRadioButton jrbtnAMais;
    private javax.swing.JRadioButton jrbtnAMenos;
    private javax.swing.JRadioButton jrbtnBMais;
    private javax.swing.JRadioButton jrbtnBMenos;
    private javax.swing.JRadioButton jrbtnOMais;
    private javax.swing.JRadioButton jrbtnOMenos;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNascimento;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfUF;
    // End of variables declaration//GEN-END:variables
}
