/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 *
 * @author 66191006317
 */
public class GUIUsuario extends javax.swing.JFrame implements InternalFrameListener {

    /**
     * Criar um modelo de tabela padrão, com o nome das colunas. O
     * defaultTableModel será o responsável pela criação de um modelo de tabela
     * com o cabeçalho que quisermos. Para isto precisamos declarar ele como
     * variável global da classe e inserir o nome das colunas que desejamos que
     * tenha na tabela.
     */
    private boolean flagGUICadastrarDoador = false;
    private boolean flagGUICadastrarHospitais = false;
    private boolean flagGUIManutencaoDoador = false;
    private boolean flagGUIManutencaoHospital = false;
    private boolean flagGUITabelaQPDPQ = false;

    /**
     * Creates new form GUIPrincipal
     */
    public GUIUsuario() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpAreaDeTrabalho = new javax.swing.JDesktopPane();
        jLabel4 = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jmCadastrar = new javax.swing.JMenu();
        jmiCadDoadores = new javax.swing.JMenuItem();
        jmiCadHospitais = new javax.swing.JMenuItem();
        jmManutencao = new javax.swing.JMenu();
        jmiManuDoador = new javax.swing.JMenuItem();
        jmiManuHospital = new javax.swing.JMenuItem();
        jmServicos = new javax.swing.JMenu();
        jmiTabelaQPDPQ = new javax.swing.JMenuItem();
        jmSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco de Sangue SGBD");
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1100, 720));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logoM.jpg"))); // NOI18N

        jdpAreaDeTrabalho.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpAreaDeTrabalhoLayout = new javax.swing.GroupLayout(jdpAreaDeTrabalho);
        jdpAreaDeTrabalho.setLayout(jdpAreaDeTrabalhoLayout);
        jdpAreaDeTrabalhoLayout.setHorizontalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpAreaDeTrabalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdpAreaDeTrabalhoLayout.setVerticalGroup(
            jdpAreaDeTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        jmCadastrar.setText("Cadastrar");

        jmiCadDoadores.setText("Doadores");
        jmiCadDoadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadDoadoresActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCadDoadores);

        jmiCadHospitais.setText("Hospitais");
        jmiCadHospitais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCadHospitaisActionPerformed(evt);
            }
        });
        jmCadastrar.add(jmiCadHospitais);

        jMenu.add(jmCadastrar);

        jmManutencao.setText("Manutenção");

        jmiManuDoador.setText("Doador");
        jmiManuDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManuDoadorActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManuDoador);

        jmiManuHospital.setText("Hospital");
        jmiManuHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiManuHospitalActionPerformed(evt);
            }
        });
        jmManutencao.add(jmiManuHospital);

        jMenu.add(jmManutencao);

        jmServicos.setText("Serviços");

        jmiTabelaQPDPQ.setText("Tabela: Quem Pode Doar para Quem");
        jmiTabelaQPDPQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTabelaQPDPQActionPerformed(evt);
            }
        });
        jmServicos.add(jmiTabelaQPDPQ);

        jMenu.add(jmServicos);

        jmSair.setText("Sair");
        jmSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmSairMouseClicked(evt);
            }
        });
        jmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSairActionPerformed(evt);
            }
        });
        jMenu.add(jmSair);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpAreaDeTrabalho)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirCadastrarDoador() {
        if (flagGUICadastrarDoador == false) {
            //Criando o objeto e estanciando a classe
            GUICadastrarSe gCD = new GUICadastrarSe();
            gCD.setTitle("Cadastrar Doador");

            //adicionando o objeto (janela) na área de trabalho
            jdpAreaDeTrabalho.add(gCD);

            //Setando a visibilidade como "true" para a janela aparecer para o usuário
            gCD.setVisible(true);

            //Setando o flagGUIClientes como verdadeiro, indicando que a janela foi aberta.
            flagGUICadastrarDoador = true;

            //Setando a janela na lista de ouvidores
            gCD.addInternalFrameListener(this);
        }
    }
    
    private void abrirCadastrarHospitais() {
        if (flagGUICadastrarHospitais == false) {
            //Criando o objeto e estanciando a classe
            GUICadastrarHospitais gCH = new GUICadastrarHospitais();

            //adicionando o objeto (janela) na área de trabalho
            jdpAreaDeTrabalho.add(gCH);

            //Setando a visibilidade como "true" para a janela aparecer para o usuário
            gCH.setVisible(true);

            //Setando o flagGUIClientes como verdadeiro, indicando que a janela foi aberta.
            flagGUICadastrarHospitais = true;

            //Setando a janela na lista de ouvidores
            gCH.addInternalFrameListener(this);
        }
    }

    private void abrirManutencaoDoador() {
        if (flagGUIManutencaoDoador == false) {
            //Criando o objeto e estanciando a classe
            GUIManutencaoDoador gMD = new GUIManutencaoDoador();

            //adicionando o objeto (janela) na área de trabalho
            jdpAreaDeTrabalho.add(gMD);

            //Setando a visibilidade como "true" para a janela aparecer para o usuário
            gMD.setVisible(true);

            //Setando o flagGUIClientes como verdadeiro, indicando que a janela foi aberta.
            flagGUIManutencaoDoador = true;

            //Setando a janela na lista de ouvidores
            gMD.addInternalFrameListener(this);
        }
    }

    private void abrirManutencaoHospital() {
        if (flagGUIManutencaoHospital == false) {
            //Criando o objeto e estanciando a classe
            GUIManutencaoHospital gMH = new GUIManutencaoHospital();

            //adicionando o objeto (janela) na área de trabalho
            jdpAreaDeTrabalho.add(gMH);

            //Setando a visibilidade como "true" para a janela aparecer para o usuário
            gMH.setVisible(true);

            //Setando o flagGUIClientes como verdadeiro, indicando que a janela foi aberta.
            flagGUIManutencaoHospital = true;

            //Setando a janela na lista de ouvidores
            gMH.addInternalFrameListener(this);
        }
    }
    
    private void abrirTabelaQPDPQ() {
        if (flagGUITabelaQPDPQ == false) {
            //Criando o objeto e estanciando a classe
            GUITabelaQPDPQ gTQ = new GUITabelaQPDPQ();

            //adicionando o objeto (janela) na área de trabalho
            jdpAreaDeTrabalho.add(gTQ);

            //Setando a visibilidade como "true" para a janela aparecer para o usuário
            gTQ.setVisible(true);

            //Setando o flagGUIClientes como verdadeiro, indicando que a janela foi aberta.
            flagGUITabelaQPDPQ = true;

            //Setando a janela na lista de ouvidores
            gTQ.addInternalFrameListener(this);
        }
    
    }

    private void jmiManuDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManuDoadorActionPerformed
        // TODO add your handling code here:
        abrirManutencaoDoador();
    }//GEN-LAST:event_jmiManuDoadorActionPerformed

    private void jmiManuHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiManuHospitalActionPerformed
        // TODO add your handling code here:
        abrirManutencaoHospital();
    }//GEN-LAST:event_jmiManuHospitalActionPerformed

    private void jmiCadDoadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadDoadoresActionPerformed
        // TODO add your handling code here:
        abrirCadastrarDoador();
    }//GEN-LAST:event_jmiCadDoadoresActionPerformed

    private void jmiCadHospitaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCadHospitaisActionPerformed
        // TODO add your handling code here:
        abrirCadastrarHospitais();
    }//GEN-LAST:event_jmiCadHospitaisActionPerformed

    private void jmiTabelaQPDPQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTabelaQPDPQActionPerformed
        // TODO add your handling code here:
        abrirTabelaQPDPQ();
    }//GEN-LAST:event_jmiTabelaQPDPQActionPerformed

    private void jmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmSairActionPerformed

    private void jmSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmSairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JDesktopPane jdpAreaDeTrabalho;
    private javax.swing.JMenu jmCadastrar;
    private javax.swing.JMenu jmManutencao;
    private javax.swing.JMenu jmSair;
    private javax.swing.JMenu jmServicos;
    private javax.swing.JMenuItem jmiCadDoadores;
    private javax.swing.JMenuItem jmiCadHospitais;
    private javax.swing.JMenuItem jmiManuDoador;
    private javax.swing.JMenuItem jmiManuHospital;
    private javax.swing.JMenuItem jmiTabelaQPDPQ;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        if (ife.getInternalFrame() instanceof GUIManutencaoDoador) {
            flagGUIManutencaoDoador = false;
        } else if (ife.getInternalFrame() instanceof GUIManutencaoHospital) {
            flagGUIManutencaoHospital = false;
        } else if (ife.getInternalFrame() instanceof GUICadastrarHospitais) {
            flagGUICadastrarHospitais = false;
        } else if (ife.getInternalFrame() instanceof GUITabelaQPDPQ) {
            flagGUITabelaQPDPQ = false;
        } else if (ife.getInternalFrame()instanceof GUICadastrarSe) {
            flagGUICadastrarDoador = false;
        }

    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {

    }
}
